# Generated by Django 3.0.4 on 2020-04-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registroarchivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaingreso', models.DateField(verbose_name='Fecha')),
                ('guianro', models.CharField(max_length=20, verbose_name='Tramite Nro')),
                ('usuario', models.CharField(max_length=200, verbose_name='Usuario')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('oficio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero Oficio')),
                ('fechaentrega', models.DateField(null=True, verbose_name='Fecha Entrega')),
                ('enviadoa', models.TextField(blank=True, max_length=250, null=True, verbose_name='Enviado a')),
                ('observacion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observacion')),
                ('atendido', models.BooleanField(default=False, verbose_name='Atendido')),
            ],
            options={
                'verbose_name': 'Tramite',
                'verbose_name_plural': 'Tramites Externos',
                'ordering': ['-fechaingreso'],
            },
        ),
    ]
