# Generated by Django 3.0.4 on 2020-04-21 00:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarchivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroarchivos',
            name='observacion',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True, verbose_name='Observacion'),
        ),
    ]
