# Generated by Django 3.0.4 on 2020-04-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarchivo', '0002_auto_20200420_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroarchivos',
            name='documentos',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
