# Generated by Django 3.0.4 on 2020-04-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarchivo', '0003_registroarchivos_documentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroarchivos',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
