# Generated by Django 3.0.6 on 2020-05-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarchivo', '0005_archivosinternos'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivosinternos',
            name='secuencia',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
