# Generated by Django 3.0.6 on 2020-05-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarchivo', '0006_archivosinternos_secuencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivosinternos',
            name='dependencia',
            field=models.CharField(default='Externa', max_length=250, null=True, verbose_name='Dependencia'),
        ),
        migrations.AlterField(
            model_name='archivosinternos',
            name='guianro',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nro Memo/Oficio'),
        ),
    ]
