# Generated by Django 3.0.6 on 2020-05-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarchivo', '0007_auto_20200519_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivosinternos',
            name='fechadespacho',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Despacho'),
        ),
    ]
